<?php

namespace Servinow\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
     public function findCategoriasByRestaurante($restauranteId){
        return $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Categoria")
                ->findBy(array('restaurante'=>$restauranteId));
    }
}
