<?php

namespace Servinow\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoRepository extends EntityRepository
{
     public function findPlatosbyRestaurant($restauranteId){
        return $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Plato")
                ->findBy(array('restaurante'=>$restauranteId));
    }
    
    public function deletePlatobyID($platoId){
        $em = $this->getEntityManager();
        
        $plato = $em->getRepository("ServinowEntitiesBundle:Plato")
                ->find($platoId);
        
        $em->remove($plato);
        $em->flush();
    }
}
