<?php

namespace Servinow\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function findProductoId($restauranteId, $productoId){
        $producto = $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Producto")
                ->findOneBy(array('id'=>$productoId, 'restaurante'=>$restauranteId));
        return $producto;
    }
    
    public function updateProductoById($RestauranteId, $productoId, $nombre, $descripcion, $precio, $disponible){
        $producto = $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Producto")
                ->findOneBy(array('id'=>$productoId, 'restaurante'=>$RestauranteId));
        $em = $this->getEntityManager();
        $producto->setNombre($nombre);
        $producto->setDescripcion($descripcion);
        $producto->setPrecio(doubleval($precio));
        $producto->setDisponible($disponible);
        $em->flush();
    }

    public function findProductosTop10Ingresos($fecha_inicio, $fecha_fin, $restaurante){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('prod.id', 'prod.nombre', 'SUM(l.cantidad * prod.precio) AS total')
                ->from('ServinowEntitiesBundle:Pedido', 'ped')
                ->where($qb->expr()->andX(
                        $qb->expr()->gte('ped.fecha', $fecha_inicio),
                        $qb->expr()->lte('ped.fecha', $fecha_fin),
                        $qb->expr()->eq('ped.restaurante', $restaurante),
                        $qb->expr()->eq('ped.pagado', true)
                ))->leftJoin('ped.lineasPedido', 'l')
                ->leftJoin('l.producto', 'prod')
                ->groupBy('prod.id')
                ->orderBy('total', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function findProductosTop10Cantidad($fecha_inicio, $fecha_fin, $restaurante){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('prod.id', 'prod.nombre', 'SUM(l.cantidad) AS total')
                ->from('ServinowEntitiesBundle:Pedido', 'ped')
                ->where($qb->expr()->andX(
                        $qb->expr()->gte('ped.fecha', $fecha_inicio),
                        $qb->expr()->lte('ped.fecha', $fecha_fin),
                        $qb->expr()->eq('ped.restaurante', $restaurante),
                        $qb->expr()->eq('ped.pagado', true)
                ))->leftJoin('ped.lineasPedido', 'l')
                ->leftJoin('l.producto', 'prod')
                ->groupBy('prod.id')
                ->orderBy('total', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function findProductoCantidadIngresos($producto, $fecha_inicio, $fecha_fin, $restaurante){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('prod.id', 'prod.nombre', 'SUM(l.cantidad) AS cantidad', 
                'SUM(l.cantidad * prod.precio) AS ingresos')
                ->from('ServinowEntitiesBundle:Pedido', 'ped')
                ->where($qb->expr()->andX(
                        $qb->expr()->gte('ped.fecha', $fecha_inicio),
                        $qb->expr()->lte('ped.fecha', $fecha_fin),
                        $qb->expr()->eq('ped.restaurante', $restaurante),
                        $qb->expr()->eq('prod.id', $producto),
                        $qb->expr()->eq('ped.pagado', true)
                ))->leftJoin('ped.lineasPedido', 'l')
                ->leftJoin('l.producto', 'prod');
        return $qb->getQuery()->getSingleResult();
    }
    
    public function setCategoriasOfProducto($restauranteId, $productoId, $categoriasId) {
        $repository = $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Categoria");
        
        $categorias = $repository->findCategoriasByRestaurante($restauranteId);        
        
        foreach ($categorias as $categoria) {
            $repository->removeProductoFromCategoria($categoria->getId(), $productoId);
        }
        
        foreach ($categoriasId as $categoriaId) {
            $repository->addProductoToCategoria($categoriaId, $productoId);
        }
    }
}
