<?php

namespace Servinow\EntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function findProductoId($restauranteId, $productoId){
        $producto = $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Producto")
                ->findOneBy(array('id'=>$productoId, 'restaurante'=>$restauranteId));
        return $producto;
    }
    
    public function updateProductoById($RestauranteId, $productoId, $nombre, $descripcion, $precio, $disponible){
        $producto = $this->getEntityManager()->getRepository("ServinowEntitiesBundle:Producto")
                ->findOneBy(array('id'=>$productoId, 'restaurante'=>$RestauranteId));
        $em = $this->getEntityManager();
        $producto->setNombre($nombre);
        $producto->setDescripcion($descripcion);
     /*   $producto->setPrecio(doubleval($doublePrecio)); */
        $producto->setDisponible($disponible);
        $em->flush();
    }
    
}
