Servinow\RestaurantDrawerBundle\Entity\SimpleObject:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    x:
      type: integer
    y:
      type: integer
    wide:
      type: integer
    tall:
      type: integer
    name:
      type: string
  manyToOne:
    _restaurant:
      targetEntity: Servinow\EntitiesBundle\Entity\Restaurante
      joinColumn:
        name: restaurante_id
        referencedColumnName: id
        onDelete: cascade
    _drawer:
      targetEntity: Servinow\RestaurantDrawerBundle\Entity\Drawer
      inversedBy: simpleObjects
      joinColumn:
        name: drawer_id
        referencedColumnName: id
        onDelete: cascade