parameters:
#    servinow_api.example.class: Servinow\ApiBundle\Example

services:
#    servinow_api.example:
#        class: %servinow_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
