parameters:
#    servinow_gestion_pedidos.example.class: Servinow\GestionPedidosBundle\Example

services:
#    servinow_gestion_pedidos.example:
#        class: %servinow_gestion_pedidos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
